lint

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,15 +28,28 @@ jobs:
           build: npm run export
           start: npm run serve
 
-  ts-prune:
+  lint:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: ts-prune
-        shell: bash
-        run:
-          ts-prune --ignore "/*.stories.tsx | src/pages/*" |
-            grep -v -E "src/(app|pages)/.* - (default|GET|dynamic)" |
-            grep -v getServerSideProps |
-            (! grep -v -E "(ts-prune --ignore|Done in |npm run)")
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v3
+        with:
+          node-version: '20.10.0'
+      - uses: actions/cache@v3 # https://github.com/cypress-io/github-action/tree/v4.2.2#install-cypress-only
+        id: node_modules_cache_id
+        with:
+          path: node_modules
+          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
+      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
+        name: Install dependencies
+        run: npm ci
+      - run: npm run lint
+      - run: npm run tsc
+      - run: output=$(npm run prune | grep -Ev 'used in module|src\\pages|\\cypress')
+             if [ -z "$output" ]; then
+               echo "Test passed - no output"
+             else
+               echo "Test failed - output detected"
+               echo "$output"
+               exit 1
+             fi
